# Generated by Django 3.2.12 on 2024-04-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_question_paricipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='paricipants',
            new_name='participants',
        ),
    ]
